# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    input_sync: true
    default_config: simple_config
    configs:
        simple_config:
            toolbar:
                - {
                    name: "styles",
                    items:
                    [
                        "Bold",
                        "Italic",
                        "BulletedList",
                        "NumberedList",
                        "Outdent",
                        "Indent",
                        "Link",
                        "PasteText",
                        "PasteFromWord",
                        "Table",
                        "Source"
                    ],
                }
            jquery: true
        # forcePasteAsPlainText: true
